Issue #132 Fixed
GetStream/stream-python pull request #133
Opened 2022-01-14 09:15 UTC by SidAtNSIO

## Summary:

Issue #132 is fixed by decoding the token from bytes to string so the string can concatenate.
## Submitter checklist:
- [x] `CHANGELOG`  N/A
- [x] Documentation N/A

## Merger checklist:
- [x] ALL tests have passed
- [x] Code Review is done
- [x] Dependencies satisfied

## Dependencies:

- [x]

2022-01-14 11:42 UTC, peterdeme commented on stream/feed.py
> +        self.token = token.decode('utf-8')
This isn't forward compatible. Please do this:

```suggestion
        self.token = token.decode('utf-8') if isinstance(token, bytes) else token
```

2022-01-14 11:46 UTC, peterdeme requested changes
- please fix the logic with my suggestion
- can you please add a test for the constructor of `Feed` class?

something like this
```py
with_bytes = Feed("thing", "thing", b"token")
assert with_bytes.token == "token"

with_str = Feed("thing, "thing", "token")
assert with_bytes.token == "token"
```

2022-01-15 15:15 UTC, SidAtNSIO commented
@peterdeme added suggested changes and test cases. please have a look.
If there is anything that I can do please let me know.
Thanks & Regards.

2022-01-15 17:50 UTC, peterdeme approved these changes
lgtm

2022-01-15 17:51 UTC, peterdeme commented
@ferhatelmas it requires your approval

2022-01-18 22:57 UTC, ferhatelmas approved these changes
LGTM

2022-01-18 22:58 UTC, merged